# Generated by Django 5.1.1 on 2024-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandDetails",
            fields=[
                (
                    "land_details_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("parcel_number", models.CharField(max_length=255, unique=True)),
                ("date_acquired", models.DateField()),
                (
                    "land_description",
                    models.TextField(default="No description provided"),
                ),
                ("price", models.FloatField(default=0.0)),
                ("owner_name", models.CharField(max_length=25)),
                (
                    "previous_owner",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("national_id", models.CharField(default="0", max_length=20)),
                ("address", models.CharField(max_length=30)),
                ("date_sold", models.DateField(blank=True, null=True)),
                ("date_purchased", models.DateField(blank=True, null=True)),
                ("location_name", models.CharField(max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
