# Generated by Django 5.1.2 on 2024-10-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetails',
            name='interested',
            field=models.BooleanField(default=False),
        ),
    ]
