# Generated by Django 5.1.1 on 2024-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0002_landdetails_interested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landdetails",
            name="interested",
        ),
        migrations.AddField(
            model_name="landdetails",
            name="interested_buyer_contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
