# Generated by Django 5.1.1 on 2024-10-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0003_remove_landdetails_interested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landdetails",
            name="interested",
            field=models.BooleanField(default=False),
        ),
    ]
