# Generated by Django 5.1.1 on 2024-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0004_landdetails_interested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landdetails",
            name="interested_buyer_contact",
        ),
        migrations.AddField(
            model_name="landdetails",
            name="interested_buyer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
