# Generated by Django 5.1.1 on 2024-10-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0003_landdetails_seller"),
        ("landDetails", "0005_remove_landdetails_interested_buyer_contact_and_more"),
    ]

    operations = []
