# Generated by Django 5.1.1 on 2024-11-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0006_merge_20241012_0958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landdetails",
            name="interested_buyer",
        ),
    ]
