# Generated by Django 5.1.1 on 2024-09-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landDetails", "0001_initial"),
        ("land_sellers", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landseller",
            name="LandDetail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_land_detail",
                to="landDetails.landdetails",
            ),
        ),
    ]
