# Generated by Django 5.1.1 on 2024-09-21 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
        ("landDetails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreements",
            name="LandDetail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to="landDetails.landdetails",
            ),
        ),
    ]
