# Generated by Django 5.1.1 on 2024-09-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0003_agreements_buyer_agreements_lawyer_agreements_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agreements",
            old_name="LandDetail",
            new_name="parcel_number",
        ),
    ]
