# Generated by Django 5.1.1 on 2024-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0004_rename_landdetail_agreements_parcel_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreements",
            name="remaining_amount",
        ),
        migrations.AlterField(
            model_name="agreements",
            name="agreed_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="agreements",
            name="down_payment",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
