# Generated by Django 5.1.1 on 2024-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0006_alter_agreements_agreed_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreements",
            name="remaining_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
