# Generated by Django 5.1.1 on 2024-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0009_agreements_remaining_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreements",
            name="remaining_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="agreements",
            name="total_amount_made",
            field=models.FloatField(default=0.0),
        ),
    ]
