# Generated by Django 5.1.1 on 2024-10-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0003_message_user_alter_message_sender_chatroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invited_by",
            field=models.CharField(max_length=100),
        ),
    ]
